server:
  port: 8887
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/login-db
    username: avicenne
    password: shoptop

  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

#The authorization server key uri address to fetch the public key and verify the signature of the access token
# https://github.com/dalirouissi/spring-social-with-angular-and-spring-security
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
