server:
  port: 8887
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/login-db
    username: avicenne
    password: shoptop

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy


app:
  secretkey: 926D96C90030DD58429D2751AC1BDBBC

